# MiraiWhitelist
# 作者：poikcue（会挽雕弓如满月 西北望 射天狼）
通用:
  运行白名单命令: 我的世界原版服务端
  可启用:
   内置白名单系统: 启用
   # 设为 不启用 则不启用此功能。
文本消息:
  群聊中标准白名单模式所寻找的关键字: +#
  群聊中管理员强制添加白名单所寻找的关键字: "%#"
  游戏内强制添加白名单成功信息: "&a已成功强制为 &f%qq% &r&a添加 &f%id% &a的白名单。"
  游戏内强制添加白名单但是已经申请过有效白名单: "&c此玩家已申请过白名单并已通过。"
  启用内置白名单系统后无白名单玩家踢出时屏幕显示的信息: |-
    &c对不起！您还&l未被添加至白名单&r&c。
    &c请您添加到群 &l600427272 &r&c后按照指示完成白名单引导工作。
  正版玩家成功添加白名单祝贺: |-
    @%name% 您所请求的白名单（%ID%）已被添加。现在，您可以使用下列域（和版本）访问服务器了！
    - mc.cubegarden.cn (1.18.2)
    祝您游戏愉快。
  群聊中强制添加白名单机器人统一回复消息: 已请求强制添加参数为 "%arg%" 的白名单。
  请求非正版白名单时群聊中通知信息: |-
    @%name% 当我们尝试请求您的白名单（%ID%）时发现该ID似乎为非正版。
    请检查拼写后重试。若正确，请与管理员联系！
  请求我的世界国际版本官方应用编程接口网络异常: |-
    @%name% 请求您的白名单（%ID%）时与Mojang API连接异常。请检查或稍后重试。
  此账户已经申请过白名单时通知信息: |-
    @%name% 您的账户似乎已经存在可用的白名单了。
    若您没有进行过此操作，请与管理员联系。
  账户未曾经申请过有效白名单但目标玩家已在白名单列表中: |-
    @%name% 您请求的目标白名单（%ID%）已经在白名单中了。
    若您无法访问服务器，请与管理员联系。
  加入群聊时欢迎消息: |-
    @%name% 欢迎来到CubeGarden！
    如需为您的账户申请白名单，请输入：“+#<您的ID>”
  请求者没有强制添加白名单的权限: "&c你没有权限强制添加白名单！"
  重新加载:
    成功时向操作者发送的消息: "&a成功重载！"
    请求者没有重新加载的权限: "&c你没有权限这么做！"

数据:
  '2':
    通用单一标识符: 1111-1111-1111-1111

内置白名单列表:
  '1111-1111-1111-1111': 已加入