# MiraiWhitelist
# 作者: poikcue
# 请在 (Java服务端)/plugins 内放入MiraiMC.
# 本插件以 MiraiMC 1.6.1为依赖，使用时，可能需要进行一定的配置。
Message:
  ReplaceGroupMessageTAG: +#
  ReplaceForceGroupMessageTAG: "!#Add "
  ReplaceForceConfirmMessageTAG: "!#Confirm "
  ForceMessage: |-
    ## 强行添加白名单警告 ##
    感谢您对CubeGarden的支持！
    您即将强行为一个 Minecraft 账户添加到白名单：
     - %ID%
    请确认您的ID是否正确。如正确，请输入"!#Confirm %ID%"
    如果不正确，您可以修改后输入"!#Confirm <正确的ID>"
    如果一切正常，请使用"+#<ID>"申请您的白名单，这是安全的。
    ## 关于更多强行添加白名单的潜在风险，请详见: ##
    ## docs.poikcue.com/whitelist/Force-add-warn/ ##
    祝您一切顺利。
  ForceConfirmMessage: |-
    ## 强行添加白名单 ##
    感谢您对CubeGarden的支持！
    您的白名单已被添加。祝您游戏愉快。
    如果您依然无法连接到服务器，请与管理员联系。
    谢谢！
  PremiumMinecraftAccountMessage: |-
    感谢对CubeGarden的支持！
    您的白名单已被添加。现在，您可以使用下列域(和版本)访问服务器了！
     - mc.cubegarden.cn (1.18.2)
    祝您游戏愉快。
    (如果您看到了这句话，那么意味着您此时申请的为 EA 服务器白名单。)
    (如果您是服务器管理员，您可以在 ~/plugins/MiraiWhitelist/config.yml 中修改这些话！)
  CrackedMinecraftAccountAlert: |-
    感谢您对CubeGarden的支持！
    很抱歉通知您: 您所请求的ID为非正版账户！
    请检查您所发送的ID的拼写，然后重试。
    祝您生活愉快。
    (如果您确认您的正版账户有效，请联系管理员进行人工核查白名单！)
  UrlError: |-
    感谢您对CubeGarden的支持！
    很抱歉的通知您：
    您目前的请求出现了一些问题。这应该由您的拼写问题引起的，请检查。
    (如果您依然认为这是由于网络或API问题，请与管理员联系。)
  AlreadySignedUp: |-
    您好！
    您所使用的账户已经向 CubeGarden 提交了一次白名单申请请求并已通过。
    如果您认为这是一个错误，请向管理员报告。
    祝您生活愉快。

# 如果你不清楚(下面)部分的用途，请不要修改它。
# 下面的文本用于数据存储。每完成请求(成功)一次白名单，都会在下方被添加或被修改。
# ** 第二部分 **
# 关于玩家的数据部分。
Data:
  # 这里是一个示例文本。请在实际使用时删除它。
  # 下方有一些基本的数据。
  2: 1111-1111-1111-1111
  # 此处的“2”即实际的QQ号。
  # 此处的一串“1”即实际玩家的UUID。这里随便用个字符替代了，因为我懒。
  # 想删除此QQ对应的UUID，只需删除。
