# MiraiWhitelist
# 作者: poikcue
# 请在 (Java服务端)/plugins 内放入MiraiMC.
# 本插件以 MiraiMC 1.7-pre3为依赖，使用时，可能需要进行一定的配置。
Message:
  ReplaceGroupMessageTAG: +#
  GroupCommandTAG: "%#"
  ForceInGameMessage: "&a已成功强制为 &f%qq% &r&a添加 &f%id% &a的白名单。"
  ForceInGameUnsuccessfulMessage: "&c此玩家已申请过白名单并已通过。"
  PremiumMinecraftAccountMessage: |-
    感谢对CubeGarden的支持！
    您所请求的白名单（%ID%）已被添加。现在，您可以使用下列域(和版本)访问服务器了！
     - mc.cubegarden.cn (1.18.2)
    祝您游戏愉快。
  ForceAdd: 已请求强制添加参数为 "%arg%" 的白名单。
  CrackedMinecraftAccountAlert: |-
    感谢您对CubeGarden的支持！
    很抱歉通知您: 您的所请求的ID（%ID%）为非正版账户！
    请检查您所发送的ID的拼写，然后重试。
    祝您生活愉快。
    (如果您确认您的正版账户有效，请向管理员请求强制添加！)
  UrlError: |-
    感谢您对CubeGarden的支持！
    很抱歉的通知您：
    您目前的请求出现了一些问题。这应该由您的拼写问题引起的。
    请检查是否含有中文及其它非法字符（%ID%），然后重试。
    (如果您依然认为这是由于网络或API问题，请向管理员请求强制添加。)
  AlreadySignedUp: |-
    您好！
    您所使用的账户已经向 CubeGarden 提交了一次白名单申请请求并已通过。
    如果您认为这是一个错误，请向管理员报告。
    祝您生活愉快。
  Reload:
    Success: "&a成功重载！"
    Without-permission: "&c你没有权限这么做！"

# 如果你不清楚(下面)部分的用途，请不要修改它。
# 下面的文本用于数据存储。每完成请求(成功)一次白名单，都会在下方被添加或被修改。
# ** 第二部分 **
# 关于玩家的数据部分。
Data:
  # 这里是一个示例文本。请在实际使用时删除它。
  # 下方有一些基本的数据。
  '2':
    UUID: 1111-1111-1111-1111
  # 此处的“2”即实际的QQ号。
  # 此处的一串“1”即实际玩家的UUID。这里随便用个字符替代了，因为我懒。
  # 想删除此QQ对应的UUID，只需删除。
