name: MiraiWhitelist
main: com.poikcue.MiraiWhitelist.Main
version: 1.2.2
api-version: 1.13
depend: [MiraiMC]
commands:
  miraiwhitelist:
    usage: "/miraiwhitelist"
    description: "New way of auto-add whitelist."